/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MedicalRecordForm,
    MedicalRecordFormFromJSON,
    MedicalRecordFormToJSON,
} from '../models';

export interface MedicalRecordIdPutRequest {
    id: number;
    medicalRecordForm?: MedicalRecordForm;
}

/**
 * 
 */
export class MedicalRecordApi extends runtime.BaseAPI {

    /**
     */
    async medicalRecordIdPutRaw(requestParameters: MedicalRecordIdPutRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling medicalRecordIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/MedicalRecord/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MedicalRecordFormToJSON(requestParameters.medicalRecordForm),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async medicalRecordIdPut(requestParameters: MedicalRecordIdPutRequest): Promise<void> {
        await this.medicalRecordIdPutRaw(requestParameters);
    }

}
