/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SummaryDto,
    SummaryDtoFromJSON,
    SummaryDtoToJSON,
} from '../models';

/**
 * 
 */
export class SummaryApi extends runtime.BaseAPI {

    /**
     */
    async getSummaryRaw(): Promise<runtime.ApiResponse<SummaryDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SummaryDtoFromJSON(jsonValue));
    }

    /**
     */
    async getSummary(): Promise<SummaryDto> {
        const response = await this.getSummaryRaw();
        return await response.value();
    }

}
