/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentForm
 */
export interface AppointmentForm {
    /**
     * 
     * @type {number}
     * @memberof AppointmentForm
     */
    physicianId?: number;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentForm
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof AppointmentForm
     */
    description?: string | null;
}

export function AppointmentFormFromJSON(json: any): AppointmentForm {
    return AppointmentFormFromJSONTyped(json, false);
}

export function AppointmentFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'physicianId': !exists(json, 'physicianId') ? undefined : json['physicianId'],
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AppointmentFormToJSON(value?: AppointmentForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'physicianId': value.physicianId,
        'time': value.time === undefined ? undefined : (value.time.toISOString()),
        'description': value.description,
    };
}


