/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AppointmentState {
    Created = 'Created',
    InProgress = 'InProgress',
    Finished = 'Finished'
}

export function AppointmentStateFromJSON(json: any): AppointmentState {
    return AppointmentStateFromJSONTyped(json, false);
}

export function AppointmentStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentState {
    return json as AppointmentState;
}

export function AppointmentStateToJSON(value?: AppointmentState | null): any {
    return value as any;
}

