/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartmentCreationForm
 */
export interface DepartmentCreationForm {
    /**
     * 
     * @type {number}
     * @memberof DepartmentCreationForm
     */
    hospitalId?: number;
    /**
     * 
     * @type {string}
     * @memberof DepartmentCreationForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentCreationForm
     */
    section?: string | null;
}

export function DepartmentCreationFormFromJSON(json: any): DepartmentCreationForm {
    return DepartmentCreationFormFromJSONTyped(json, false);
}

export function DepartmentCreationFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentCreationForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hospitalId': !exists(json, 'hospitalId') ? undefined : json['hospitalId'],
        'name': json['name'],
        'section': !exists(json, 'section') ? undefined : json['section'],
    };
}

export function DepartmentCreationFormToJSON(value?: DepartmentCreationForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hospitalId': value.hospitalId,
        'name': value.name,
        'section': value.section,
    };
}


