/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalCreationForm
 */
export interface HospitalCreationForm {
    /**
     * 
     * @type {string}
     * @memberof HospitalCreationForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HospitalCreationForm
     */
    address: string;
}

export function HospitalCreationFormFromJSON(json: any): HospitalCreationForm {
    return HospitalCreationFormFromJSONTyped(json, false);
}

export function HospitalCreationFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalCreationForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'],
    };
}

export function HospitalCreationFormToJSON(value?: HospitalCreationForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': value.address,
    };
}


