/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalDto
 */
export interface HospitalDto {
    /**
     * 
     * @type {number}
     * @memberof HospitalDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof HospitalDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HospitalDto
     */
    address?: string | null;
}

export function HospitalDtoFromJSON(json: any): HospitalDto {
    return HospitalDtoFromJSONTyped(json, false);
}

export function HospitalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function HospitalDtoToJSON(value?: HospitalDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'address': value.address,
    };
}


