/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    token?: string | null;
    /**
     * 
     * @type {UserDto}
     * @memberof LoginResult
     */
    user?: UserDto;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'user': !exists(json, 'user') ? undefined : UserDtoFromJSON(json['user']),
    };
}

export function LoginResultToJSON(value?: LoginResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': UserDtoToJSON(value.user),
    };
}


