/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhysicianDto
 */
export interface PhysicianDto {
    /**
     * 
     * @type {number}
     * @memberof PhysicianDto
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof PhysicianDto
     */
    departmentId?: number;
}

export function PhysicianDtoFromJSON(json: any): PhysicianDto {
    return PhysicianDtoFromJSONTyped(json, false);
}

export function PhysicianDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicianDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'departmentId': !exists(json, 'departmentId') ? undefined : json['departmentId'],
    };
}

export function PhysicianDtoToJSON(value?: PhysicianDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'departmentId': value.departmentId,
    };
}


