/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DepartmentDto,
    DepartmentDtoFromJSON,
    DepartmentDtoFromJSONTyped,
    DepartmentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface PhysicianDto
 */
export interface PhysicianDto {
    /**
     * 
     * @type {number}
     * @memberof PhysicianDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PhysicianDto
     */
    name?: string | null;
    /**
     * 
     * @type {DepartmentDto}
     * @memberof PhysicianDto
     */
    department?: DepartmentDto;
}

export function PhysicianDtoFromJSON(json: any): PhysicianDto {
    return PhysicianDtoFromJSONTyped(json, false);
}

export function PhysicianDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicianDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'department': !exists(json, 'department') ? undefined : DepartmentDtoFromJSON(json['department']),
    };
}

export function PhysicianDtoToJSON(value?: PhysicianDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'department': DepartmentDtoToJSON(value.department),
    };
}


