/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhysicianRegisterForm
 */
export interface PhysicianRegisterForm {
    /**
     * 
     * @type {number}
     * @memberof PhysicianRegisterForm
     */
    physicianId?: number;
}

export function PhysicianRegisterFormFromJSON(json: any): PhysicianRegisterForm {
    return PhysicianRegisterFormFromJSONTyped(json, false);
}

export function PhysicianRegisterFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicianRegisterForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'physicianId': !exists(json, 'physicianId') ? undefined : json['physicianId'],
    };
}

export function PhysicianRegisterFormToJSON(value?: PhysicianRegisterForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'physicianId': value.physicianId,
    };
}


