/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AppointmentDto,
    AppointmentDtoFromJSON,
    AppointmentDtoFromJSONTyped,
    AppointmentDtoToJSON,
    MedicalRecordDto,
    MedicalRecordDtoFromJSON,
    MedicalRecordDtoFromJSONTyped,
    MedicalRecordDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface SummaryDto
 */
export interface SummaryDto {
    /**
     * 
     * @type {AppointmentDto}
     * @memberof SummaryDto
     */
    recentAppointment?: AppointmentDto;
    /**
     * 
     * @type {MedicalRecordDto}
     * @memberof SummaryDto
     */
    recentMedicalRecord?: MedicalRecordDto;
}

export function SummaryDtoFromJSON(json: any): SummaryDto {
    return SummaryDtoFromJSONTyped(json, false);
}

export function SummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recentAppointment': !exists(json, 'recentAppointment') ? undefined : AppointmentDtoFromJSON(json['recentAppointment']),
        'recentMedicalRecord': !exists(json, 'recentMedicalRecord') ? undefined : MedicalRecordDtoFromJSON(json['recentMedicalRecord']),
    };
}

export function SummaryDtoToJSON(value?: SummaryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recentAppointment': AppointmentDtoToJSON(value.recentAppointment),
        'recentMedicalRecord': MedicalRecordDtoToJSON(value.recentMedicalRecord),
    };
}


