/* tslint:disable */
/* eslint-disable */
/**
 * MsaasBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Gender,
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateUserForm
 */
export interface UpdateUserForm {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserForm
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserForm
     */
    password?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof UpdateUserForm
     */
    gender?: Gender;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserForm
     */
    birthday?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserForm
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserForm
     */
    email?: string | null;
}

export function UpdateUserFormFromJSON(json: any): UpdateUserForm {
    return UpdateUserFormFromJSONTyped(json, false);
}

export function UpdateUserFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'gender': !exists(json, 'gender') ? undefined : GenderFromJSON(json['gender']),
        'birthday': !exists(json, 'birthday') ? undefined : (json['birthday'] === null ? null : new Date(json['birthday'])),
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UpdateUserFormToJSON(value?: UpdateUserForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'gender': GenderToJSON(value.gender),
        'birthday': value.birthday === undefined ? undefined : (value.birthday === null ? null : value.birthday.toISOString().substr(0,10)),
        'phone': value.phone,
        'email': value.email,
    };
}


