name: Test
on:
  push:
    branches:
      - web
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
    - run: yarn install
    - run: yarn test
